### ISSUE TITLE
No redirection after login.

### ISSUE THREAD

**Issue by dakdevs** [wohali/ips4-oauth2-server#2] opened 2016-06-16 05:53 UTC
It seems that if a user is not logged in, it redirects to the login correctly. Although, upon logging in, it does not redirect back to the oauth url for authorization.

**Comment by wohali** [comment] 2016-06-16 17:22
Strange, I can't reproduce this. I explicitly tested this very scenario. Can you give me any further detail to reproduce the bug?

**Comment by wohali** [comment] 2016-06-21 19:46
@Vinlock:

Your application calls:

```
http://your-ips4-site.com/applications/oauth2server/interface/authorize.php
```

If you are NOT logged into IPS4, you get a redirect to:

```
https://your-ips4-site.com/login/?ref=XXXXXXXXXXXXXXXXN0LWlwczQuZ290ci51cy9hcHBsaWNhdGlvbnMvb2F1dGgyc2VydmVyL2ludGVyZmFjZS9hdXRob3JpemUucGhwPw%3D%3D
```

I need ^^^ this URL from BEFORE you log in, specifically the `?ref=` section.

-Joan

**Comment by wohali** [comment] 2016-06-29 21:03
Someone recently contacted me with a redirect issue. It turned out that they were using `http://` instead of `https://` URLs in their application (their IPS4 site is served over `https`.) Setting the URLs in their application to `https://` fixed their problem. Perhaps this is of some use to you.

@Vinlock I am going to close this issue, please reopen if you have any further information.

**Closed as completed by wohali** 2016-06-29 21:03 UTC

**Comment by dakdevs** [comment] 2016-07-06 23:41
Sorry I did not respond to this! Haven't had too much computer time aside from a few things I need to do  😢. Although, thank you so much for responding to let me know. Much appreciated!!!
